sudo: false
dist: trusty

# With the readiness of github action, now travis CI only needs to run on master
branches:
  only:
    - master

language: java
jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - gradle wrapper

jobs:
  include:
    - stage: "WeID-Java-SDK CI"
      script:
        - chmod u+x .ci/script/build-ci.sh
        - .ci/script/build-ci.sh
        - travis_wait 40 ./gradlew check
        - ./gradlew jacocoTestReport
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: "dependency pipeline"
      script:
        - chmod u+x .ci/script/weid-http-service/build-ci.sh
        - .ci/script/weid-http-service/build-ci.sh
      name: "HTTP Rest Service simple CI"
      if: (branch = master)
    - stage: "dependency pipeline"
      script:
        - chmod +x .ci/script/weid-sample/build-ci.sh
        - .ci/script/weid-sample/build-ci.sh
      name: "Sample simple CI"
      if: (branch = master)
#    - stage: "dependency pipeline"
#      script:
#        - chmod u+x .ci/script/weid-build-tools/build-ci.sh
#        - .ci/script/weid-build-tools/build-ci.sh
#      name: "Build Tools simple CI"
#      if: (branch = master)

deploy:
  provider: releases
  api_key: $GIT_REPO_TOKEN
  file_glob: true
  file: dist/app/weid-java-sdk*.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
